import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { localDateKey } from "@/lib/date";

type SignalSeverity = "critical" | "high" | "medium" | "low";

type CommandSignal = {
  id: string;
  module: string;
  title: string;
  detail: string;
  severity: SignalSeverity;
  href: string;
  action: string;
  sortScore: number;
};

type AutopilotBriefResponse = {
  ok: boolean;
  generatedAt: string;
  health: "critical" | "attention" | "stable";
  counts: {
    kpis: number;
    projects: number;
    socialDrafts: number;
    assets: number;
    events: number;
    birthdays: number;
    aiDrafts: number;
    newsItems: number;
    signals: number;
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  signals: CommandSignal[];
  topSignals: CommandSignal[];
  briefText: string;
  message?: string;
};

type AutopilotAction =
  | "create_social_draft"
  | "create_ai_review_draft";

function todayDate() {
  return localDateKey();
}

function formatDate() {
  return new Intl.DateTimeFormat("en-NG", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date());
}

function buildSignalSummary(signals: CommandSignal[]) {
  if (signals.length === 0) {
    return "No urgent signals were detected. DevonOS recommends using this window to prepare, polish, and get ahead.";
  }

  return signals
    .slice(0, 5)
    .map((signal, index) => {
      return `${index + 1}. ${signal.title}\nModule: ${signal.module}\nPriority: ${signal.severity.toUpperCase()}\nAction: ${signal.action}`;
    })
    .join("\n\n");
}

function buildSocialCaption(brief: AutopilotBriefResponse) {
  const topSignals = buildSignalSummary(brief.topSignals);

  return [
    "Daily Communications Priority Watch",
    "",
    `Date: ${formatDate()}`,
    "",
    "Today’s command signals show the following priority areas:",
    "",
    topSignals,
    "",
    "Recommended focus:",
    "Review urgent items first, confirm pending approvals, prepare upcoming communication moments, and keep the content pipeline clean.",
    "",
    "Generated by DevonOS Autopilot.",
  ].join("\n");
}

function buildVisualDirection(brief: AutopilotBriefResponse) {
  return [
    "Create a premium white-and-blue command update visual.",
    "",
    `System health: ${brief.health.toUpperCase()}`,
    `Total signals: ${brief.counts.signals}`,
    `Critical: ${brief.counts.critical}`,
    `High priority: ${brief.counts.high}`,
    "",
    "Style:",
    "Clean enterprise layout, white background, blue/violet accents, refined cards, premium typography, no clutter, no green, no cheap AI look.",
  ].join("\n");
}

function buildAiReviewOutput(brief: AutopilotBriefResponse) {
  return [
    "DEVONOS AUTOPILOT REVIEW DRAFT",
    "",
    `Date: ${formatDate()}`,
    `System Health: ${brief.health.toUpperCase()}`,
    "",
    "What DevonOS detected:",
    buildSignalSummary(brief.topSignals),
    "",
    "Recommended review process:",
    "1. Handle critical and high-priority signals first.",
    "2. Confirm pending social posts and approval items.",
    "3. Review KPIs or projects with deadlines approaching.",
    "4. Convert relevant news or events into communication drafts.",
    "5. Mark completed items in their proper modules.",
    "",
    "Full Brief:",
    brief.briefText,
  ].join("\n");
}

async function getAutopilotBrief(request: Request) {
  const briefUrl = new URL("/api/autopilot/brief", request.url);

  const response = await fetch(briefUrl, {
    method: "GET",
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error("Could not fetch Autopilot brief.");
  }

  const data = (await response.json()) as AutopilotBriefResponse;

  if (!data.ok) {
    throw new Error(data.message || "Autopilot brief was invalid.");
  }

  return data;
}

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const action = String(body.action ?? "") as AutopilotAction;

    const brief = await getAutopilotBrief(request);

    if (action === "create_social_draft") {
      const platform = String(body.platform ?? "X");
      const title = `Autopilot Daily Priority Draft - ${formatDate()}`;

      const draft = await prisma.socialDraft.create({
        data: {
          title,
          campaign: "DevonOS Autopilot",
          platform,
          status: "Draft",
          scheduledDate: todayDate(),
          caption: buildSocialCaption(brief),
          visualDirection: buildVisualDirection(brief),
          hashtags:
            "#DevonOS #Communications #Productivity #CommandCenter",
          notes:
            "Generated automatically by DevonOS Autopilot from the daily command brief. Review before posting.",
        },
      });

      return NextResponse.json({
        ok: true,
        action,
        createdType: "socialDraft",
        href: "/social",
        message:
          "DevonOS created a Social Studio draft from today’s command brief.",
        record: draft,
      });
    }

    if (action === "create_ai_review_draft") {
      const title = `Autopilot Review Draft - ${formatDate()}`;

      const draft = await prisma.aiDraft.create({
        data: {
          title,
          category: "Report",
          tone: "Professional",
          status: "Generated",
          instruction:
            "Review this Autopilot command brief, refine the priorities, and prepare an executive-ready daily action summary.",
          sourceText: brief.briefText,
          output: buildAiReviewOutput(brief),
          notes:
            "Generated automatically by DevonOS Autopilot. Use this to review the day’s workload and prepare a clean summary.",
        },
      });

      return NextResponse.json({
        ok: true,
        action,
        createdType: "aiDraft",
        href: "/ai",
        message:
          "DevonOS created an AI Studio review draft from today’s command brief.",
        record: draft,
      });
    }

    return NextResponse.json(
      {
        ok: false,
        message:
          "Unknown Autopilot action. Use create_social_draft or create_ai_review_draft.",
      },
      { status: 400 }
    );
  } catch (error) {
    console.error("Autopilot execute failed:", error);

    return NextResponse.json(
      {
        ok: false,
        message: "DevonOS Autopilot could not execute this action.",
      },
      { status: 500 }
    );
  }
}
